In [1]:
import  numpy as np

In [4]:
input_array = np.array([10,20,30])
def z1(input_array):
    return np.append(input_array, [40,50,60,70,80,90])
z1(input_array)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
def z2(size):
    return np.indices(size).sum(axis=0) % 2
z2([8,8])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [9]:
input_array = np.array([0,12,45,21,34,99.91])
def z3(input_array: np.array):
    return (input_array - 32) * 5 / 9
z3(input_array)

array([-17.77777778, -11.11111111,   7.22222222,  -6.11111111,
         1.11111111,  37.72777778])

In [12]:
def z4():
    output = np.zeros([4,4])
    for i in range(4):
        output[i,i] = i+4
    return output
z4()

array([[4., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 7.]])

In [20]:
input_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
def z5(input_array):
    return np.flip(input_array.reshape(9))
z5(input_array)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [33]:
input_array = np.arange(0,100).reshape([10,10])
def z6(input_array):
    return input_array[np.logical_and(input_array % 2 == 0, input_array % 3 != 0)]
z6(input_array)


array([ 2,  4,  8, 10, 14, 16, 20, 22, 26, 28, 32, 34, 38, 40, 44, 46, 50,
       52, 56, 58, 62, 64, 68, 70, 74, 76, 80, 82, 86, 88, 92, 94, 98])

In [40]:
def z7(min_value = 0, max_value= 1, wyznacznik = 0):
    output = np.random.randint(min_value, max_value, [10, 10])
    return output, np.linalg.det(output) 
z7(max_value=10)

(array([[2, 3, 2, 0, 0, 4, 8, 0, 4, 5],
        [1, 1, 9, 7, 2, 2, 3, 3, 5, 9],
        [5, 3, 2, 1, 4, 7, 4, 6, 3, 6],
        [1, 2, 4, 9, 2, 8, 9, 3, 7, 7],
        [0, 3, 3, 2, 8, 3, 5, 7, 1, 1],
        [7, 9, 0, 7, 0, 9, 7, 6, 7, 6],
        [0, 0, 4, 6, 8, 5, 8, 1, 2, 2],
        [4, 5, 4, 4, 5, 3, 5, 8, 5, 1],
        [8, 3, 4, 3, 1, 5, 3, 6, 4, 9],
        [4, 9, 6, 9, 0, 3, 8, 8, 2, 3]]),
 -84793074.0000002)