In [25]:
import numpy as np
from collections import Counter

In [4]:
def z1(matrix, to_find):
    return to_find in matrix
print(z1(np.array([[1,2],[3,4]]), 0))
print(z1(np.array([[1,2],[3,4]]), 1))

False
True


In [5]:
def z2(array: np.array):
    return array.mean()
z2(np.array([1,2,3,4,5]))

3.0

In [7]:
def z3(array1, array2):
    return np.dot(array1, array2)
z3([1,2,3],[4,5,6])

32

In [10]:
def z4(size: int, value: int):
    return np.array(size*size*[value]).reshape([size,size])
z4(3,2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
def z5():
    pass

In [13]:
def z6(array):
    array[array<0] = 0
    return array
z6(np.array([1,-1,1,-1,2,-2]))

array([1, 0, 1, 0, 2, 0])

In [24]:
def z7(matrix, n):
    return sorted(matrix.flatten(), reverse=True)[:n]
z7(np.arange(9).reshape((3,3)), 2)

[8, 7]

In [30]:
def z8(matrix):
    return max(x:=Counter(matrix.flatten()), key=x.get)
print(z8(np.array([[2, 2, 2],[2, 2, 2],[2, 2, 2]])))
print(z8(np.array([1,2,2,3,3,3,3,4,5,6])))

2
3


In [36]:
def z9(matrix):
    return np.unique(matrix)
z9(np.array([[1,2],[2,3]]))

array([1, 2, 3])

In [33]:
def z10(p1 ,p2):
    return ((p2[0]-p1[0])**2+(p2[1]-p1[1])**2)**(1/2)
z9([0,0],[4,4])

5.656854249492381