In [67]:
import pandas as pd
import numpy as np

In [68]:
i = pd.read_csv('inbody_out.csv')
a = pd.read_csv('antropo_out.csv', sep=";")

In [69]:
a.head()


Unnamed: 0   id data.badania DataBadania  Wysokosc  WysokoscSiedzeniowa  \
0           0  101   2015.09.25  2015.09.25     182.0                 96.0   
1           1  102   2015.09.25  2015.09.25     167.0                 84.4   
2           2  104   2015.09.25  2015.09.25     187.4                 93.5   
3           3  105   2015.09.25  2015.09.25     177.9                 90.0   
4           4  107   2015.09.25  2015.09.25     161.7                 84.8   

   ObwodSzyi  ObwodKlatkiPiersiowej  ObwodKlatkiPiersiowejWdech  ObwodPasa  \
0       39.0                   86.0                        89.0       83.0   
1       31.0                   72.5                        76.0       62.0   
2       35.0                   83.0                        84.0       68.0   
3       33.0                   80.0                        86.0       68.0   
4       35.0                   90.0                        93.0       88.0   

   ...  SzerokoscBarkow  SzerokoscBioder  SzerokoscKlatkiPiersiowej  \
0  ...             38.0             27.0                       27.0   
1  ...             32.8             23.8                       24.1   
2  ...             39.4             27.3                       26.5   
3  ...             37.0             26.8                       26.0   
4  ...             34.0             28.0                       26.0   

   GlebokoscKlatkiPiersiowej  FaldNaRamieniu  FaldPodLopatka  FaldNaBrzuchu  \
0                       21.0            14.0            10.0           19.0   
1                       17.4            12.0             4.0            6.0   
2                       19.1             5.0             9.0            4.0   
3                       17.7            11.0             6.0            8.0   
4                       20.0            31.0            35.0           46.0   

   CisnienieKrwiSkurczowe  CisnienieKrwiRozkurczowe  TetnoKrwi  
0                   128.0                      69.0       66.0  
1                   128.0                      60.0       75.0  
2                   146.0                      83.0        NaN  
3                   121.0                      80.0       92.0  
4                   119.0                      67.0       88.0  

[5 rows x 23 columns]

In [70]:
i.head()

Unnamed: 0   id DateOfBirth   Age  Sex           DataBadania  Weight  \
0           0  101  14.06.2000  15.3    1  2015.09.25. 09:13:11    80.5   
1           1  102  27.12.2000  14.7    1  2015.09.25. 09:20:27    48.8   
2           2  104  06.11.2000  14.8    1  2015.09.25. 09:34:48    63.5   
3           3  105  22.07.2000  15.2    1  2015.09.25. 09:37:26    59.1   
4           4  107  24.06.2002  13.3    1  2015.09.25. 09:55:02    72.2   

   LowerLimit_WeightNormalRange_  UpperLimit_WeightNormalRange_  \
0                           62.7                           84.8   
1                           51.2                           69.3   
2                           66.1                           89.5   
3                           59.8                           80.8   
4                           46.9                           63.5   

   TBW_TotalBodyWater_  ...  MeasuredCircumferenceofRightArm  \
0                 49.8  ...                              NaN   
1                 31.7  ...                              NaN   
2                 42.6  ...                              NaN   
3                 39.8  ...                              NaN   
4                 33.1  ...                              NaN   

   MeasuredCircumferenceofLeftArm  MeasuredCircumferenceofRightThigh  \
0                             NaN                                NaN   
1                             NaN                                NaN   
2                             NaN                                NaN   
3                             NaN                                NaN   
4                             NaN                                NaN   

   MeasuredCircumferenceofLeftThigh  GrowthScore  ObesityDegreeofaChild  \
0                               NaN        123.0                  111.0   
1                               NaN         85.0                   83.0   
2                               NaN        102.0                   82.0   
3                               NaN         98.0                   87.0   
4                               NaN         59.0                  137.0   

   LowerLimit_ObesityDegreeofaChildNormalRange_  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   

   UpperLimit_ObesityDegreeofaChildNormalRange_  InBodyType  LocalID  
0                                           NaN       230.0      NaN  
1                                           NaN       230.0      NaN  
2                                           NaN       230.0      NaN  
3                                           NaN       230.0      NaN  
4                                           NaN       230.0      NaN  

[5 rows x 108 columns]

In [71]:
id = np.sort(a["id"].unique())
print(id)

[101 102 104 105 107 108 109 111 112 115 116 117 118 119 121 122 123 124
 125 126 127 128 129 130 131 132 133 135 136 137 139 140 141 142 143 144
 146 147 149 150 151 153 154 155 156 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 174 175 176 177 178 179 180 181 183 184 185 186 187
 188 190 191 192 194 195 197 200 202 203 204 208 209 210 211 212 213 214
 215 216 217 218 219 220 224 226 228 232 233 234 235 236 237 238 239 241
 242 243 244 245 246 247 249 250 251 252 254 255 256 258 261 263 266 267
 301 302 303 304 305 307 309 310 311 312 314 315 316 317 318 325 326 400
 405 406 501 502 503 504 505 507 508 509 510 511 601 981 982 983 984 986
 987 992 993 994 995 996 997 998 999]


In [72]:
lk_a = len(a.columns) -1
lk_i = len(i.columns) -1
lw = len(id)
lk = lk_a*9 + lk_i*9+1
m = np.zeros((lw, lk))

In [73]:
print(m)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [74]:
kolumny = ["ID"] + [f"{x}_{i}" for x in a.columns[1:] for i in range(9)]
print(kolumny)


['ID', 'id_0', 'id_1', 'id_2', 'id_3', 'id_4', 'id_5', 'id_6', 'id_7', 'id_8', 'data.badania_0', 'data.badania_1', 'data.badania_2', 'data.badania_3', 'data.badania_4', 'data.badania_5', 'data.badania_6', 'data.badania_7', 'data.badania_8', 'DataBadania_0', 'DataBadania_1', 'DataBadania_2', 'DataBadania_3', 'DataBadania_4', 'DataBadania_5', 'DataBadania_6', 'DataBadania_7', 'DataBadania_8', 'Wysokosc_0', 'Wysokosc_1', 'Wysokosc_2', 'Wysokosc_3', 'Wysokosc_4', 'Wysokosc_5', 'Wysokosc_6', 'Wysokosc_7', 'Wysokosc_8', 'WysokoscSiedzeniowa_0', 'WysokoscSiedzeniowa_1', 'WysokoscSiedzeniowa_2', 'WysokoscSiedzeniowa_3', 'WysokoscSiedzeniowa_4', 'WysokoscSiedzeniowa_5', 'WysokoscSiedzeniowa_6', 'WysokoscSiedzeniowa_7', 'WysokoscSiedzeniowa_8', 'ObwodSzyi_0', 'ObwodSzyi_1', 'ObwodSzyi_2', 'ObwodSzyi_3', 'ObwodSzyi_4', 'ObwodSzyi_5', 'ObwodSzyi_6', 'ObwodSzyi_7', 'ObwodSzyi_8', 'ObwodKlatkiPiersiowej_0', 'ObwodKlatkiPiersiowej_1', 'ObwodKlatkiPiersiowej_2', 'ObwodKlatkiPiersiowej_3', 'ObwodKlatki

In [75]:
#TODO naprawić to 
#for i in id:
#    doSortowania = a[a["id"] == i]
#    for x in doSortowania.values:
#        kandydaci = []
#        if(".09." in x[2] or "-09-" in x[2]):
#            if "2015" in x[2]:
#                pomiar = 1
#            elif "2016" in x[2]:
#                kandydaci = [2,3]
#        else:
#            kandydaci = []
#        for k in lk_a:
#            m[i][k] = x[k]
#        
#
#    break

In [77]:
#TODO uzupełnić bo nie zdążyłem na zajęciach
for index, row in i.iterrows():
    for k in lk_i:
        m[row,(k-1)*9+pomiar+1+len(lk_a)*9] = a[??,k+1]
    break;

101
